services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: hackverse  # <-- Ajoutez cette ligne
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
